// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_log.proto

package com.yxsd.kanshu.log;


import org.apache.commons.lang.StringUtils;

public final class ClientLog {
  private ClientLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientlogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.log.Clientlog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
     */
    java.util.List<Clientlog.OperLog>
        getOperLogList();
    /**
     * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
     */
    Clientlog.OperLog getOperLog(int index);
    /**
     * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
     */
    int getOperLogCount();
    /**
     * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
     */
    java.util.List<? extends Clientlog.OperLogOrBuilder>
        getOperLogOrBuilderList();
    /**
     * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
     */
    Clientlog.OperLogOrBuilder getOperLogOrBuilder(int index);
  }
  /**
   * Protobuf type {@code proto.log.Clientlog}
   */
  public static final class Clientlog extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.log.Clientlog)
      ClientlogOrBuilder {
    // Use Clientlog.newBuilder() to construct.
    private Clientlog(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Clientlog(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Clientlog defaultInstance;
    public static Clientlog getDefaultInstance() {
      return defaultInstance;
    }

    public Clientlog getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Clientlog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                operLog_ = new java.util.ArrayList<OperLog>();
                mutable_bitField0_ |= 0x00000001;
              }
              operLog_.add(input.readMessage(OperLog.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          operLog_ = java.util.Collections.unmodifiableList(operLog_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientLog.internal_static_proto_log_Clientlog_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientLog.internal_static_proto_log_Clientlog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Clientlog.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Clientlog> PARSER =
        new com.google.protobuf.AbstractParser<Clientlog>() {
      public Clientlog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Clientlog(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Clientlog> getParserForType() {
      return PARSER;
    }

    public interface OperLogOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.log.Clientlog.OperLog)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string ptt = 1;</code>
       */
      boolean hasPtt();
      /**
       * <code>optional string ptt = 1;</code>
       */
      String getPtt();
      /**
       * <code>optional string ptt = 1;</code>
       */
      com.google.protobuf.ByteString
          getPttBytes();

      /**
       * <code>optional string pfp = 2;</code>
       */
      boolean hasPfp();
      /**
       * <code>optional string pfp = 2;</code>
       */
      String getPfp();
      /**
       * <code>optional string pfp = 2;</code>
       */
      com.google.protobuf.ByteString
          getPfpBytes();

      /**
       * <code>optional string pft = 3;</code>
       */
      boolean hasPft();
      /**
       * <code>optional string pft = 3;</code>
       */
      String getPft();
      /**
       * <code>optional string pft = 3;</code>
       */
      com.google.protobuf.ByteString
          getPftBytes();

      /**
       * <code>optional string pip = 4;</code>
       */
      boolean hasPip();
      /**
       * <code>optional string pip = 4;</code>
       */
      String getPip();
      /**
       * <code>optional string pip = 4;</code>
       */
      com.google.protobuf.ByteString
          getPipBytes();

      /**
       * <code>optional string did = 5;</code>
       */
      boolean hasDid();
      /**
       * <code>optional string did = 5;</code>
       */
      String getDid();
      /**
       * <code>optional string did = 5;</code>
       */
      com.google.protobuf.ByteString
          getDidBytes();

      /**
       * <code>optional string uploaddate = 6;</code>
       */
      boolean hasUploaddate();
      /**
       * <code>optional string uploaddate = 6;</code>
       */
      String getUploaddate();
      /**
       * <code>optional string uploaddate = 6;</code>
       */
      com.google.protobuf.ByteString
          getUploaddateBytes();

      /**
       * <code>optional string version = 7;</code>
       */
      boolean hasVersion();
      /**
       * <code>optional string version = 7;</code>
       */
      String getVersion();
      /**
       * <code>optional string version = 7;</code>
       */
      com.google.protobuf.ByteString
          getVersionBytes();

      /**
       * <code>optional string uid = 8;</code>
       */
      boolean hasUid();
      /**
       * <code>optional string uid = 8;</code>
       */
      String getUid();
      /**
       * <code>optional string uid = 8;</code>
       */
      com.google.protobuf.ByteString
          getUidBytes();

      /**
       * <code>optional string cnid = 9;</code>
       */
      boolean hasCnid();
      /**
       * <code>optional string cnid = 9;</code>
       */
      String getCnid();
      /**
       * <code>optional string cnid = 9;</code>
       */
      com.google.protobuf.ByteString
          getCnidBytes();

      /**
       * <code>optional string imsi = 10;</code>
       */
      boolean hasImsi();
      /**
       * <code>optional string imsi = 10;</code>
       */
      String getImsi();
      /**
       * <code>optional string imsi = 10;</code>
       */
      com.google.protobuf.ByteString
          getImsiBytes();

      /**
       * <code>optional string msg = 11;</code>
       */
      boolean hasMsg();
      /**
       * <code>optional string msg = 11;</code>
       */
      String getMsg();
      /**
       * <code>optional string msg = 11;</code>
       */
      com.google.protobuf.ByteString
          getMsgBytes();

      /**
       * <code>optional string ext = 12;</code>
       */
      boolean hasExt();
      /**
       * <code>optional string ext = 12;</code>
       */
      String getExt();
      /**
       * <code>optional string ext = 12;</code>
       */
      com.google.protobuf.ByteString
          getExtBytes();
    }
    /**
     * Protobuf type {@code proto.log.Clientlog.OperLog}
     */
    public static final class OperLog extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:proto.log.Clientlog.OperLog)
        OperLogOrBuilder {
      // Use OperLog.newBuilder() to construct.
      private OperLog(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private OperLog(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final OperLog defaultInstance;
      public static OperLog getDefaultInstance() {
        return defaultInstance;
      }

      public OperLog getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private OperLog(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                ptt_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                pfp_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                pft_ = bs;
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                pip_ = bs;
                break;
              }
              case 42: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000010;
                did_ = bs;
                break;
              }
              case 50: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000020;
                uploaddate_ = bs;
                break;
              }
              case 58: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000040;
                version_ = bs;
                break;
              }
              case 66: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000080;
                uid_ = bs;
                break;
              }
              case 74: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000100;
                cnid_ = bs;
                break;
              }
              case 82: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000200;
                imsi_ = bs;
                break;
              }
              case 90: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000400;
                msg_ = bs;
                break;
              }
              case 98: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000800;
                ext_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientLog.internal_static_proto_log_Clientlog_OperLog_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientLog.internal_static_proto_log_Clientlog_OperLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OperLog.class, Builder.class);
      }

      public static com.google.protobuf.Parser<OperLog> PARSER =
          new com.google.protobuf.AbstractParser<OperLog>() {
        public OperLog parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new OperLog(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<OperLog> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int PTT_FIELD_NUMBER = 1;
      private Object ptt_;
      /**
       * <code>optional string ptt = 1;</code>
       */
      public boolean hasPtt() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string ptt = 1;</code>
       */
      public String getPtt() {
        Object ref = ptt_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ptt_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string ptt = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPttBytes() {
        Object ref = ptt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ptt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PFP_FIELD_NUMBER = 2;
      private Object pfp_;
      /**
       * <code>optional string pfp = 2;</code>
       */
      public boolean hasPfp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string pfp = 2;</code>
       */
      public String getPfp() {
        Object ref = pfp_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pfp_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string pfp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPfpBytes() {
        Object ref = pfp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pfp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PFT_FIELD_NUMBER = 3;
      private Object pft_;
      /**
       * <code>optional string pft = 3;</code>
       */
      public boolean hasPft() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string pft = 3;</code>
       */
      public String getPft() {
        Object ref = pft_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pft_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string pft = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPftBytes() {
        Object ref = pft_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pft_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PIP_FIELD_NUMBER = 4;
      private Object pip_;
      /**
       * <code>optional string pip = 4;</code>
       */
      public boolean hasPip() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string pip = 4;</code>
       */
      public String getPip() {
        Object ref = pip_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pip_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string pip = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPipBytes() {
        Object ref = pip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DID_FIELD_NUMBER = 5;
      private Object did_;
      /**
       * <code>optional string did = 5;</code>
       */
      public boolean hasDid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string did = 5;</code>
       */
      public String getDid() {
        Object ref = did_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            did_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string did = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDidBytes() {
        Object ref = did_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          did_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int UPLOADDATE_FIELD_NUMBER = 6;
      private Object uploaddate_;
      /**
       * <code>optional string uploaddate = 6;</code>
       */
      public boolean hasUploaddate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string uploaddate = 6;</code>
       */
      public String getUploaddate() {
        Object ref = uploaddate_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uploaddate_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string uploaddate = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUploaddateBytes() {
        Object ref = uploaddate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uploaddate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VERSION_FIELD_NUMBER = 7;
      private Object version_;
      /**
       * <code>optional string version = 7;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string version = 7;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string version = 7;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int UID_FIELD_NUMBER = 8;
      private Object uid_;
      /**
       * <code>optional string uid = 8;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string uid = 8;</code>
       */
      public String getUid() {
        Object ref = uid_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uid_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string uid = 8;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CNID_FIELD_NUMBER = 9;
      private Object cnid_;
      /**
       * <code>optional string cnid = 9;</code>
       */
      public boolean hasCnid() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string cnid = 9;</code>
       */
      public String getCnid() {
        Object ref = cnid_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cnid_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string cnid = 9;</code>
       */
      public com.google.protobuf.ByteString
          getCnidBytes() {
        Object ref = cnid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cnid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int IMSI_FIELD_NUMBER = 10;
      private Object imsi_;
      /**
       * <code>optional string imsi = 10;</code>
       */
      public boolean hasImsi() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string imsi = 10;</code>
       */
      public String getImsi() {
        Object ref = imsi_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            imsi_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string imsi = 10;</code>
       */
      public com.google.protobuf.ByteString
          getImsiBytes() {
        Object ref = imsi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          imsi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MSG_FIELD_NUMBER = 11;
      private Object msg_;
      /**
       * <code>optional string msg = 11;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string msg = 11;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string msg = 11;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int EXT_FIELD_NUMBER = 12;
      private Object ext_;
      /**
       * <code>optional string ext = 12;</code>
       */
      public boolean hasExt() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string ext = 12;</code>
       */
      public String getExt() {
        Object ref = ext_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ext_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string ext = 12;</code>
       */
      public com.google.protobuf.ByteString
          getExtBytes() {
        Object ref = ext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        ptt_ = "";
        pfp_ = "";
        pft_ = "";
        pip_ = "";
        did_ = "";
        uploaddate_ = "";
        version_ = "";
        uid_ = "";
        cnid_ = "";
        imsi_ = "";
        msg_ = "";
        ext_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getPttBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getPfpBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getPftBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getPipBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBytes(5, getDidBytes());
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeBytes(6, getUploaddateBytes());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeBytes(7, getVersionBytes());
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output.writeBytes(8, getUidBytes());
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          output.writeBytes(9, getCnidBytes());
        }
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          output.writeBytes(10, getImsiBytes());
        }
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          output.writeBytes(11, getMsgBytes());
        }
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          output.writeBytes(12, getExtBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getPttBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getPfpBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getPftBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getPipBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, getDidBytes());
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(6, getUploaddateBytes());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(7, getVersionBytes());
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(8, getUidBytes());
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(9, getCnidBytes());
        }
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(10, getImsiBytes());
        }
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(11, getMsgBytes());
        }
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(12, getExtBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static OperLog parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static OperLog parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static OperLog parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static OperLog parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static OperLog parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static OperLog parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static OperLog parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static OperLog parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static OperLog parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static OperLog parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(OperLog prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.log.Clientlog.OperLog}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:proto.log.Clientlog.OperLog)
          OperLogOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ClientLog.internal_static_proto_log_Clientlog_OperLog_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ClientLog.internal_static_proto_log_Clientlog_OperLog_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  OperLog.class, Builder.class);
        }

        // Construct using com.iwanvi.proto.ClientLog.Clientlog.OperLog.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          ptt_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          pfp_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          pft_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          pip_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          did_ = "";
          bitField0_ = (bitField0_ & ~0x00000010);
          uploaddate_ = "";
          bitField0_ = (bitField0_ & ~0x00000020);
          version_ = "";
          bitField0_ = (bitField0_ & ~0x00000040);
          uid_ = "";
          bitField0_ = (bitField0_ & ~0x00000080);
          cnid_ = "";
          bitField0_ = (bitField0_ & ~0x00000100);
          imsi_ = "";
          bitField0_ = (bitField0_ & ~0x00000200);
          msg_ = "";
          bitField0_ = (bitField0_ & ~0x00000400);
          ext_ = "";
          bitField0_ = (bitField0_ & ~0x00000800);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ClientLog.internal_static_proto_log_Clientlog_OperLog_descriptor;
        }

        public OperLog getDefaultInstanceForType() {
          return OperLog.getDefaultInstance();
        }

        public OperLog build() {
          OperLog result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public OperLog buildPartial() {
          OperLog result = new OperLog(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.ptt_ = ptt_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.pfp_ = pfp_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.pft_ = pft_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.pip_ = pip_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.did_ = did_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.uploaddate_ = uploaddate_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.version_ = version_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000080;
          }
          result.uid_ = uid_;
          if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
            to_bitField0_ |= 0x00000100;
          }
          result.cnid_ = cnid_;
          if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
            to_bitField0_ |= 0x00000200;
          }
          result.imsi_ = imsi_;
          if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
            to_bitField0_ |= 0x00000400;
          }
          result.msg_ = msg_;
          if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
            to_bitField0_ |= 0x00000800;
          }
          result.ext_ = ext_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof OperLog) {
            return mergeFrom((OperLog)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(OperLog other) {
          if (other == OperLog.getDefaultInstance()) return this;
          if (other.hasPtt()) {
            bitField0_ |= 0x00000001;
            ptt_ = other.ptt_;
            onChanged();
          }
          if (other.hasPfp()) {
            bitField0_ |= 0x00000002;
            pfp_ = other.pfp_;
            onChanged();
          }
          if (other.hasPft()) {
            bitField0_ |= 0x00000004;
            pft_ = other.pft_;
            onChanged();
          }
          if (other.hasPip()) {
            bitField0_ |= 0x00000008;
            pip_ = other.pip_;
            onChanged();
          }
          if (other.hasDid()) {
            bitField0_ |= 0x00000010;
            did_ = other.did_;
            onChanged();
          }
          if (other.hasUploaddate()) {
            bitField0_ |= 0x00000020;
            uploaddate_ = other.uploaddate_;
            onChanged();
          }
          if (other.hasVersion()) {
            bitField0_ |= 0x00000040;
            version_ = other.version_;
            onChanged();
          }
          if (other.hasUid()) {
            bitField0_ |= 0x00000080;
            uid_ = other.uid_;
            onChanged();
          }
          if (other.hasCnid()) {
            bitField0_ |= 0x00000100;
            cnid_ = other.cnid_;
            onChanged();
          }
          if (other.hasImsi()) {
            bitField0_ |= 0x00000200;
            imsi_ = other.imsi_;
            onChanged();
          }
          if (other.hasMsg()) {
            bitField0_ |= 0x00000400;
            msg_ = other.msg_;
            onChanged();
          }
          if (other.hasExt()) {
            bitField0_ |= 0x00000800;
            ext_ = other.ext_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          OperLog parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (OperLog) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private Object ptt_ = "";
        /**
         * <code>optional string ptt = 1;</code>
         */
        public boolean hasPtt() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string ptt = 1;</code>
         */
        public String getPtt() {
          Object ref = ptt_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              ptt_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string ptt = 1;</code>
         */
        public com.google.protobuf.ByteString
            getPttBytes() {
          Object ref = ptt_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            ptt_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string ptt = 1;</code>
         */
        public Builder setPtt(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          ptt_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string ptt = 1;</code>
         */
        public Builder clearPtt() {
          bitField0_ = (bitField0_ & ~0x00000001);
          ptt_ = getDefaultInstance().getPtt();
          onChanged();
          return this;
        }
        /**
         * <code>optional string ptt = 1;</code>
         */
        public Builder setPttBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          ptt_ = value;
          onChanged();
          return this;
        }

        private Object pfp_ = "";
        /**
         * <code>optional string pfp = 2;</code>
         */
        public boolean hasPfp() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string pfp = 2;</code>
         */
        public String getPfp() {
          Object ref = pfp_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              pfp_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string pfp = 2;</code>
         */
        public com.google.protobuf.ByteString
            getPfpBytes() {
          Object ref = pfp_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            pfp_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string pfp = 2;</code>
         */
        public Builder setPfp(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          pfp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string pfp = 2;</code>
         */
        public Builder clearPfp() {
          bitField0_ = (bitField0_ & ~0x00000002);
          pfp_ = getDefaultInstance().getPfp();
          onChanged();
          return this;
        }
        /**
         * <code>optional string pfp = 2;</code>
         */
        public Builder setPfpBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          pfp_ = value;
          onChanged();
          return this;
        }

        private Object pft_ = "";
        /**
         * <code>optional string pft = 3;</code>
         */
        public boolean hasPft() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string pft = 3;</code>
         */
        public String getPft() {
          Object ref = pft_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              pft_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string pft = 3;</code>
         */
        public com.google.protobuf.ByteString
            getPftBytes() {
          Object ref = pft_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            pft_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string pft = 3;</code>
         */
        public Builder setPft(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          pft_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string pft = 3;</code>
         */
        public Builder clearPft() {
          bitField0_ = (bitField0_ & ~0x00000004);
          pft_ = getDefaultInstance().getPft();
          onChanged();
          return this;
        }
        /**
         * <code>optional string pft = 3;</code>
         */
        public Builder setPftBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          pft_ = value;
          onChanged();
          return this;
        }

        private Object pip_ = "";
        /**
         * <code>optional string pip = 4;</code>
         */
        public boolean hasPip() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string pip = 4;</code>
         */
        public String getPip() {
          Object ref = pip_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              pip_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string pip = 4;</code>
         */
        public com.google.protobuf.ByteString
            getPipBytes() {
          Object ref = pip_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            pip_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string pip = 4;</code>
         */
        public Builder setPip(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          pip_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string pip = 4;</code>
         */
        public Builder clearPip() {
          bitField0_ = (bitField0_ & ~0x00000008);
          pip_ = getDefaultInstance().getPip();
          onChanged();
          return this;
        }
        /**
         * <code>optional string pip = 4;</code>
         */
        public Builder setPipBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          pip_ = value;
          onChanged();
          return this;
        }

        private Object did_ = "";
        /**
         * <code>optional string did = 5;</code>
         */
        public boolean hasDid() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional string did = 5;</code>
         */
        public String getDid() {
          Object ref = did_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              did_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string did = 5;</code>
         */
        public com.google.protobuf.ByteString
            getDidBytes() {
          Object ref = did_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            did_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string did = 5;</code>
         */
        public Builder setDid(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          did_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string did = 5;</code>
         */
        public Builder clearDid() {
          bitField0_ = (bitField0_ & ~0x00000010);
          did_ = getDefaultInstance().getDid();
          onChanged();
          return this;
        }
        /**
         * <code>optional string did = 5;</code>
         */
        public Builder setDidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          did_ = value;
          onChanged();
          return this;
        }

        private Object uploaddate_ = "";
        /**
         * <code>optional string uploaddate = 6;</code>
         */
        public boolean hasUploaddate() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional string uploaddate = 6;</code>
         */
        public String getUploaddate() {
          Object ref = uploaddate_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              uploaddate_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string uploaddate = 6;</code>
         */
        public com.google.protobuf.ByteString
            getUploaddateBytes() {
          Object ref = uploaddate_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            uploaddate_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string uploaddate = 6;</code>
         */
        public Builder setUploaddate(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          uploaddate_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string uploaddate = 6;</code>
         */
        public Builder clearUploaddate() {
          bitField0_ = (bitField0_ & ~0x00000020);
          uploaddate_ = getDefaultInstance().getUploaddate();
          onChanged();
          return this;
        }
        /**
         * <code>optional string uploaddate = 6;</code>
         */
        public Builder setUploaddateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          uploaddate_ = value;
          onChanged();
          return this;
        }

        private Object version_ = "";
        /**
         * <code>optional string version = 7;</code>
         */
        public boolean hasVersion() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional string version = 7;</code>
         */
        public String getVersion() {
          Object ref = version_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              version_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string version = 7;</code>
         */
        public com.google.protobuf.ByteString
            getVersionBytes() {
          Object ref = version_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            version_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string version = 7;</code>
         */
        public Builder setVersion(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          version_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string version = 7;</code>
         */
        public Builder clearVersion() {
          bitField0_ = (bitField0_ & ~0x00000040);
          version_ = getDefaultInstance().getVersion();
          onChanged();
          return this;
        }
        /**
         * <code>optional string version = 7;</code>
         */
        public Builder setVersionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          version_ = value;
          onChanged();
          return this;
        }

        private Object uid_ = "";
        /**
         * <code>optional string uid = 8;</code>
         */
        public boolean hasUid() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>optional string uid = 8;</code>
         */
        public String getUid() {
          Object ref = uid_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              uid_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string uid = 8;</code>
         */
        public com.google.protobuf.ByteString
            getUidBytes() {
          Object ref = uid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            uid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string uid = 8;</code>
         */
        public Builder setUid(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
          uid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string uid = 8;</code>
         */
        public Builder clearUid() {
          bitField0_ = (bitField0_ & ~0x00000080);
          uid_ = getDefaultInstance().getUid();
          onChanged();
          return this;
        }
        /**
         * <code>optional string uid = 8;</code>
         */
        public Builder setUidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
          uid_ = value;
          onChanged();
          return this;
        }

        private Object cnid_ = "";
        /**
         * <code>optional string cnid = 9;</code>
         */
        public boolean hasCnid() {
          return ((bitField0_ & 0x00000100) == 0x00000100);
        }
        /**
         * <code>optional string cnid = 9;</code>
         */
        public String getCnid() {
          Object ref = cnid_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              cnid_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string cnid = 9;</code>
         */
        public com.google.protobuf.ByteString
            getCnidBytes() {
          Object ref = cnid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            cnid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string cnid = 9;</code>
         */
        public Builder setCnid(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
          cnid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string cnid = 9;</code>
         */
        public Builder clearCnid() {
          bitField0_ = (bitField0_ & ~0x00000100);
          cnid_ = getDefaultInstance().getCnid();
          onChanged();
          return this;
        }
        /**
         * <code>optional string cnid = 9;</code>
         */
        public Builder setCnidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
          cnid_ = value;
          onChanged();
          return this;
        }

        private Object imsi_ = "";
        /**
         * <code>optional string imsi = 10;</code>
         */
        public boolean hasImsi() {
          return ((bitField0_ & 0x00000200) == 0x00000200);
        }
        /**
         * <code>optional string imsi = 10;</code>
         */
        public String getImsi() {
          Object ref = imsi_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              imsi_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string imsi = 10;</code>
         */
        public com.google.protobuf.ByteString
            getImsiBytes() {
          Object ref = imsi_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            imsi_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string imsi = 10;</code>
         */
        public Builder setImsi(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
          imsi_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string imsi = 10;</code>
         */
        public Builder clearImsi() {
          bitField0_ = (bitField0_ & ~0x00000200);
          imsi_ = getDefaultInstance().getImsi();
          onChanged();
          return this;
        }
        /**
         * <code>optional string imsi = 10;</code>
         */
        public Builder setImsiBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
          imsi_ = value;
          onChanged();
          return this;
        }

        private Object msg_ = "";
        /**
         * <code>optional string msg = 11;</code>
         */
        public boolean hasMsg() {
          return ((bitField0_ & 0x00000400) == 0x00000400);
        }
        /**
         * <code>optional string msg = 11;</code>
         */
        public String getMsg() {
          Object ref = msg_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              msg_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string msg = 11;</code>
         */
        public com.google.protobuf.ByteString
            getMsgBytes() {
          Object ref = msg_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            msg_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string msg = 11;</code>
         */
        public Builder setMsg(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
          msg_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string msg = 11;</code>
         */
        public Builder clearMsg() {
          bitField0_ = (bitField0_ & ~0x00000400);
          msg_ = getDefaultInstance().getMsg();
          onChanged();
          return this;
        }
        /**
         * <code>optional string msg = 11;</code>
         */
        public Builder setMsgBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
          msg_ = value;
          onChanged();
          return this;
        }

        private Object ext_ = "";
        /**
         * <code>optional string ext = 12;</code>
         */
        public boolean hasExt() {
          return ((bitField0_ & 0x00000800) == 0x00000800);
        }
        /**
         * <code>optional string ext = 12;</code>
         */
        public String getExt() {
          Object ref = ext_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              ext_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string ext = 12;</code>
         */
        public com.google.protobuf.ByteString
            getExtBytes() {
          Object ref = ext_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            ext_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string ext = 12;</code>
         */
        public Builder setExt(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
          ext_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string ext = 12;</code>
         */
        public Builder clearExt() {
          bitField0_ = (bitField0_ & ~0x00000800);
          ext_ = getDefaultInstance().getExt();
          onChanged();
          return this;
        }
        /**
         * <code>optional string ext = 12;</code>
         */
        public Builder setExtBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
          ext_ = value;
          onChanged();
          return this;
        }

      public void initParse(LogItem logitem) {

          if (!StringUtils.isEmpty(logitem.getPtt())) {
              setPtt(logitem.getPtt());
          }
          if (!StringUtils.isEmpty(logitem.getPfp())) {
              setPfp(logitem.getPfp());
          }
          if (!StringUtils.isEmpty(logitem.getPft())) {
              setPft(logitem.getPft());
          }

          if (!StringUtils.isEmpty(logitem.getPip())) {
              setPip(logitem.getPip());
          }
          if (!StringUtils.isEmpty(logitem.getDid())) {
              setDid(logitem.getDid());
          }
          if (!StringUtils.isEmpty(logitem.getUploaddate())) {
              setUploaddate(logitem.getUploaddate());
          }
          if (!StringUtils.isEmpty(logitem.getVersion())) {
              setVersion(logitem.getVersion());
          }
          if (!StringUtils.isEmpty(logitem.getUid())) {
              setUid(logitem.getUid());
          }
          if (!StringUtils.isEmpty(logitem.getCnid())) {
              setCnid(logitem.getCnid());
          }
          if (!StringUtils.isEmpty(logitem.getImsi())) {
              setImsi(logitem.getImsi());
          }
          if (!StringUtils.isEmpty(logitem.getMsg())) {
              setMsg(logitem.getMsg());
          }
          if (!StringUtils.isEmpty(logitem.getExt())) {
              setExt(logitem.getExt());
          }
      }

          // @@protoc_insertion_point(builder_scope:proto.log.Clientlog.OperLog)
      }

      static {
        defaultInstance = new OperLog(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:proto.log.Clientlog.OperLog)
    }

    public static final int OPERLOG_FIELD_NUMBER = 1;
    private java.util.List<OperLog> operLog_;
    /**
     * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
     */
    public java.util.List<OperLog> getOperLogList() {
      return operLog_;
    }
    /**
     * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
     */
    public java.util.List<? extends OperLogOrBuilder>
        getOperLogOrBuilderList() {
      return operLog_;
    }
    /**
     * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
     */
    public int getOperLogCount() {
      return operLog_.size();
    }
    /**
     * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
     */
    public OperLog getOperLog(int index) {
      return operLog_.get(index);
    }
    /**
     * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
     */
    public OperLogOrBuilder getOperLogOrBuilder(
        int index) {
      return operLog_.get(index);
    }

    private void initFields() {
      operLog_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < operLog_.size(); i++) {
        output.writeMessage(1, operLog_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < operLog_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, operLog_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Clientlog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Clientlog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Clientlog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Clientlog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Clientlog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Clientlog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Clientlog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Clientlog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Clientlog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Clientlog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Clientlog prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.log.Clientlog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.log.Clientlog)
        ClientlogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientLog.internal_static_proto_log_Clientlog_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientLog.internal_static_proto_log_Clientlog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Clientlog.class, Builder.class);
      }

      // Construct using com.iwanvi.proto.ClientLog.Clientlog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOperLogFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (operLogBuilder_ == null) {
          operLog_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          operLogBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientLog.internal_static_proto_log_Clientlog_descriptor;
      }

      public Clientlog getDefaultInstanceForType() {
        return Clientlog.getDefaultInstance();
      }

      public Clientlog build() {
        Clientlog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Clientlog buildPartial() {
        Clientlog result = new Clientlog(this);
        int from_bitField0_ = bitField0_;
        if (operLogBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            operLog_ = java.util.Collections.unmodifiableList(operLog_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.operLog_ = operLog_;
        } else {
          result.operLog_ = operLogBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Clientlog) {
          return mergeFrom((Clientlog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Clientlog other) {
        if (other == Clientlog.getDefaultInstance()) return this;
        if (operLogBuilder_ == null) {
          if (!other.operLog_.isEmpty()) {
            if (operLog_.isEmpty()) {
              operLog_ = other.operLog_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOperLogIsMutable();
              operLog_.addAll(other.operLog_);
            }
            onChanged();
          }
        } else {
          if (!other.operLog_.isEmpty()) {
            if (operLogBuilder_.isEmpty()) {
              operLogBuilder_.dispose();
              operLogBuilder_ = null;
              operLog_ = other.operLog_;
              bitField0_ = (bitField0_ & ~0x00000001);
              operLogBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOperLogFieldBuilder() : null;
            } else {
              operLogBuilder_.addAllMessages(other.operLog_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Clientlog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Clientlog) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<OperLog> operLog_ =
        java.util.Collections.emptyList();
      private void ensureOperLogIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          operLog_ = new java.util.ArrayList<OperLog>(operLog_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          OperLog, OperLog.Builder, OperLogOrBuilder> operLogBuilder_;

      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public java.util.List<OperLog> getOperLogList() {
        if (operLogBuilder_ == null) {
          return java.util.Collections.unmodifiableList(operLog_);
        } else {
          return operLogBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public int getOperLogCount() {
        if (operLogBuilder_ == null) {
          return operLog_.size();
        } else {
          return operLogBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public OperLog getOperLog(int index) {
        if (operLogBuilder_ == null) {
          return operLog_.get(index);
        } else {
          return operLogBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public Builder setOperLog(
          int index, OperLog value) {
        if (operLogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOperLogIsMutable();
          operLog_.set(index, value);
          onChanged();
        } else {
          operLogBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public Builder setOperLog(
          int index, OperLog.Builder builderForValue) {
        if (operLogBuilder_ == null) {
          ensureOperLogIsMutable();
          operLog_.set(index, builderForValue.build());
          onChanged();
        } else {
          operLogBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public Builder addOperLog(OperLog value) {
        if (operLogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOperLogIsMutable();
          operLog_.add(value);
          onChanged();
        } else {
          operLogBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public Builder addOperLog(
          int index, OperLog value) {
        if (operLogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOperLogIsMutable();
          operLog_.add(index, value);
          onChanged();
        } else {
          operLogBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public Builder addOperLog(
          OperLog.Builder builderForValue) {
        if (operLogBuilder_ == null) {
          ensureOperLogIsMutable();
          operLog_.add(builderForValue.build());
          onChanged();
        } else {
          operLogBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public Builder addOperLog(
          int index, OperLog.Builder builderForValue) {
        if (operLogBuilder_ == null) {
          ensureOperLogIsMutable();
          operLog_.add(index, builderForValue.build());
          onChanged();
        } else {
          operLogBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public Builder addAllOperLog(
          Iterable<? extends OperLog> values) {
        if (operLogBuilder_ == null) {
          ensureOperLogIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, operLog_);
          onChanged();
        } else {
          operLogBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public Builder clearOperLog() {
        if (operLogBuilder_ == null) {
          operLog_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          operLogBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public Builder removeOperLog(int index) {
        if (operLogBuilder_ == null) {
          ensureOperLogIsMutable();
          operLog_.remove(index);
          onChanged();
        } else {
          operLogBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public OperLog.Builder getOperLogBuilder(
          int index) {
        return getOperLogFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public OperLogOrBuilder getOperLogOrBuilder(
          int index) {
        if (operLogBuilder_ == null) {
          return operLog_.get(index);  } else {
          return operLogBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public java.util.List<? extends OperLogOrBuilder>
           getOperLogOrBuilderList() {
        if (operLogBuilder_ != null) {
          return operLogBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(operLog_);
        }
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public OperLog.Builder addOperLogBuilder() {
        return getOperLogFieldBuilder().addBuilder(
            OperLog.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public OperLog.Builder addOperLogBuilder(
          int index) {
        return getOperLogFieldBuilder().addBuilder(
            index, OperLog.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.log.Clientlog.OperLog operLog = 1;</code>
       */
      public java.util.List<OperLog.Builder>
           getOperLogBuilderList() {
        return getOperLogFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          OperLog, OperLog.Builder, OperLogOrBuilder>
          getOperLogFieldBuilder() {
        if (operLogBuilder_ == null) {
          operLogBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              OperLog, OperLog.Builder, OperLogOrBuilder>(
                  operLog_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          operLog_ = null;
        }
        return operLogBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.log.Clientlog)
    }

    static {
      defaultInstance = new Clientlog(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.log.Clientlog)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_log_Clientlog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_log_Clientlog_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_log_Clientlog_OperLog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_log_Clientlog_OperLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021client\037_log.proto\022\tproto.log\"\357\001\n\tClien" +
      "tlog\022-\n\007operLog\030\001 \003(\0132\034.proto.log.Client" +
      "log.OperLog\032\262\001\n\007OperLog\022\013\n\003ptt\030\001 \001(\t\022\013\n\003" +
      "pfp\030\002 \001(\t\022\013\n\003pft\030\003 \001(\t\022\013\n\003pip\030\004 \001(\t\022\013\n\003d" +
      "id\030\005 \001(\t\022\022\n\nuploaddate\030\006 \001(\t\022\017\n\007version\030" +
      "\007 \001(\t\022\013\n\003uid\030\010 \001(\t\022\014\n\004cnid\030\t \001(\t\022\014\n\004imsi" +
      "\030\n \001(\t\022\013\n\003msg\030\013 \001(\t\022\013\n\003ext\030\014 \001(\tB\022\n\020com." +
      "iwanvi.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_log_Clientlog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_log_Clientlog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_log_Clientlog_descriptor,
        new String[] { "OperLog", });
    internal_static_proto_log_Clientlog_OperLog_descriptor =
      internal_static_proto_log_Clientlog_descriptor.getNestedTypes().get(0);
    internal_static_proto_log_Clientlog_OperLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_log_Clientlog_OperLog_descriptor,
        new String[] { "Ptt", "Pfp", "Pft", "Pip", "Did", "Uploaddate", "Version", "Uid", "Cnid", "Imsi", "Msg", "Ext", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
