package com.yxsd.kanshu.log;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOG_ITEM.
 */
public class LogItem implements java.io.Serializable {

    private Long id;
    private String ptt;
    private String pfp;
    private String pft;
    private String pip;
    private String did;
    private String uploaddate;
    private String version;
    private String uid;
    private String cnid;
    private String imsi;
    private String msg;
    private String ext; //221扩展字段

    public LogItem() {
    }

    public LogItem(Long id) {
        this.id = id;
    }

    public LogItem(Long id, String ptt, String pfp, String pft, String pip, String did, String uploaddate, String version, String uid, String cnid, String imsi, String msg,String ext) {
        this.id = id;
        this.ptt = ptt;
        this.pfp = pfp;
        this.pft = pft;
        this.pip = pip;
        this.did = did;
        this.uploaddate = uploaddate;
        this.version = version;
        this.uid = uid;
        this.cnid = cnid;
        this.imsi = imsi;
        this.msg = msg;
        this.ext = ext;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPtt() {
        return ptt;
    }

    public void setPtt(String ptt) {
        this.ptt = ptt;
    }

    public String getPfp() {
        return pfp;
    }

    public void setPfp(String pfp) {
        this.pfp = pfp;
    }

    public String getPft() {
        return pft;
    }

    public void setPft(String pft) {
        this.pft = pft;
    }

    public String getPip() {
        return pip;
    }

    public void setPip(String pip) {
        this.pip = pip;
    }

    public String getDid() {
        return did;
    }

    public void setDid(String did) {
        this.did = did;
    }

    public String getUploaddate() {
        return uploaddate;
    }

    public void setUploaddate(String uploaddate) {
        this.uploaddate = uploaddate;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getCnid() {
        return cnid;
    }

    public void setCnid(String cnid) {
        this.cnid = cnid;
    }

    public String getImsi() {
        return imsi;
    }

    public void setImsi(String imsi) {
        this.imsi = imsi;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getExt() {
        return ext;
    }

    public void setExt(String ext) {
        this.ext = ext;
    }

    @Override
    public String toString() {
        return new StringBuilder().append("LogItem{").append("id=").append(id)
                .append(", pft=").append(pft)
                .append(", pfp=").append(pfp)
                .append(", did=").append(did)
                .append(", msg=").append(msg)
                .append(", ext=").append(ext).append("}").toString();
    }
}
